  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position - Joint Position Trajectory Controller -------------------
  rs007l_arm_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    constraints:
      goal_time: 2.0                   # Defaults to zero
      stopped_velocity_tolerance: 0.1 # Defaults to 0.01
      lower_joint1:
        trajectory: 0 
        goal: 0.2       
      lower_joint2:
        trajectory: 0 
        goal: 0.2       
      lower_joint3:
        trajectory: 0 
        goal: 0.2       
      lower_joint4:
        trajectory: 0 
        goal: 0.2       
#  gazebo_ros_control/pid_gains:
#    joint1:
#      p: 100.0
#      i: 0.01
#      d: 10.0
#    joint2:
#      p: 100.0
#      i: 0.01
#      d: 10.0
#    joint3:
#      p: 100.0
#      i: 0.01
#      d: 10.0
#    joint4:
#      p: 100.0
#      i: 0.01
#      d: 10.0
#    joint5:
#      p: 100.0
#      i: 0.01
#      d: 10.0
#    joint6:
#      p: 100.0
#      i: 0.01
#      d: 10.0
      
    state_publish_rate:  50 # Defaults to 50
    action_monitor_rate: 20 # Defaults to 20
    #hold_trajectory_duration: 0 # Defaults to 0
