// Generated by gencpp from file khi_rs007l_moveit_config3/autodriverResult.msg
// DO NOT EDIT!


#ifndef KHI_RS007L_MOVEIT_CONFIG3_MESSAGE_AUTODRIVERRESULT_H
#define KHI_RS007L_MOVEIT_CONFIG3_MESSAGE_AUTODRIVERRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace khi_rs007l_moveit_config3
{
template <class ContainerAllocator>
struct autodriverResult_
{
  typedef autodriverResult_<ContainerAllocator> Type;

  autodriverResult_()
    : resu(0)  {
    }
  autodriverResult_(const ContainerAllocator& _alloc)
    : resu(0)  {
  (void)_alloc;
    }



   typedef int32_t _resu_type;
  _resu_type resu;





  typedef boost::shared_ptr< ::khi_rs007l_moveit_config3::autodriverResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::khi_rs007l_moveit_config3::autodriverResult_<ContainerAllocator> const> ConstPtr;

}; // struct autodriverResult_

typedef ::khi_rs007l_moveit_config3::autodriverResult_<std::allocator<void> > autodriverResult;

typedef boost::shared_ptr< ::khi_rs007l_moveit_config3::autodriverResult > autodriverResultPtr;
typedef boost::shared_ptr< ::khi_rs007l_moveit_config3::autodriverResult const> autodriverResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::khi_rs007l_moveit_config3::autodriverResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::khi_rs007l_moveit_config3::autodriverResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace khi_rs007l_moveit_config3

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'khi_rs007l_moveit_config3': ['/home/mslab/catkin_ws/devel/share/khi_rs007l_moveit_config3/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::khi_rs007l_moveit_config3::autodriverResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::khi_rs007l_moveit_config3::autodriverResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::khi_rs007l_moveit_config3::autodriverResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::khi_rs007l_moveit_config3::autodriverResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::khi_rs007l_moveit_config3::autodriverResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::khi_rs007l_moveit_config3::autodriverResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::khi_rs007l_moveit_config3::autodriverResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4bc5b3fe34aee0ff5196e0a80c35caf3";
  }

  static const char* value(const ::khi_rs007l_moveit_config3::autodriverResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4bc5b3fe34aee0ffULL;
  static const uint64_t static_value2 = 0x5196e0a80c35caf3ULL;
};

template<class ContainerAllocator>
struct DataType< ::khi_rs007l_moveit_config3::autodriverResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "khi_rs007l_moveit_config3/autodriverResult";
  }

  static const char* value(const ::khi_rs007l_moveit_config3::autodriverResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::khi_rs007l_moveit_config3::autodriverResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result definition\n\
int32 resu\n\
";
  }

  static const char* value(const ::khi_rs007l_moveit_config3::autodriverResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::khi_rs007l_moveit_config3::autodriverResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.resu);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct autodriverResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::khi_rs007l_moveit_config3::autodriverResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::khi_rs007l_moveit_config3::autodriverResult_<ContainerAllocator>& v)
  {
    s << indent << "resu: ";
    Printer<int32_t>::stream(s, indent + "  ", v.resu);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KHI_RS007L_MOVEIT_CONFIG3_MESSAGE_AUTODRIVERRESULT_H
