// Generated by gencpp from file test1/StockRequest.msg
// DO NOT EDIT!


#ifndef TEST1_MESSAGE_STOCKREQUEST_H
#define TEST1_MESSAGE_STOCKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>

namespace test1
{
template <class ContainerAllocator>
struct StockRequest_
{
  typedef StockRequest_<ContainerAllocator> Type;

  StockRequest_()
    : a()  {
    }
  StockRequest_(const ContainerAllocator& _alloc)
    : a(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _a_type;
  _a_type a;





  typedef boost::shared_ptr< ::test1::StockRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test1::StockRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StockRequest_

typedef ::test1::StockRequest_<std::allocator<void> > StockRequest;

typedef boost::shared_ptr< ::test1::StockRequest > StockRequestPtr;
typedef boost::shared_ptr< ::test1::StockRequest const> StockRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test1::StockRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test1::StockRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace test1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'control_msgs': ['/opt/ros/kinetic/share/control_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::test1::StockRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test1::StockRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test1::StockRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test1::StockRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test1::StockRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test1::StockRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test1::StockRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e84691c9f67b66e3cd77c36cee7a3696";
  }

  static const char* value(const ::test1::StockRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe84691c9f67b66e3ULL;
  static const uint64_t static_value2 = 0xcd77c36cee7a3696ULL;
};

template<class ContainerAllocator>
struct DataType< ::test1::StockRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test1/StockRequest";
  }

  static const char* value(const ::test1::StockRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test1::StockRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/String a\n\
\n\
================================================================================\n\
MSG: std_msgs/String\n\
string data\n\
";
  }

  static const char* value(const ::test1::StockRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test1::StockRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StockRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test1::StockRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test1::StockRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.a);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST1_MESSAGE_STOCKREQUEST_H
