// Generated by gencpp from file test1/Stock.msg
// DO NOT EDIT!


#ifndef TEST1_MESSAGE_STOCK_H
#define TEST1_MESSAGE_STOCK_H

#include <ros/service_traits.h>


#include <test1/StockRequest.h>
#include <test1/StockResponse.h>


namespace test1
{

struct Stock
{

typedef StockRequest Request;
typedef StockResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Stock
} // namespace test1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test1::Stock > {
  static const char* value()
  {
    return "9d5d792114b13aea89fa9544e93bdabb";
  }

  static const char* value(const ::test1::Stock&) { return value(); }
};

template<>
struct DataType< ::test1::Stock > {
  static const char* value()
  {
    return "test1/Stock";
  }

  static const char* value(const ::test1::Stock&) { return value(); }
};


// service_traits::MD5Sum< ::test1::StockRequest> should match 
// service_traits::MD5Sum< ::test1::Stock > 
template<>
struct MD5Sum< ::test1::StockRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test1::Stock >::value();
  }
  static const char* value(const ::test1::StockRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test1::StockRequest> should match 
// service_traits::DataType< ::test1::Stock > 
template<>
struct DataType< ::test1::StockRequest>
{
  static const char* value()
  {
    return DataType< ::test1::Stock >::value();
  }
  static const char* value(const ::test1::StockRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test1::StockResponse> should match 
// service_traits::MD5Sum< ::test1::Stock > 
template<>
struct MD5Sum< ::test1::StockResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test1::Stock >::value();
  }
  static const char* value(const ::test1::StockResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test1::StockResponse> should match 
// service_traits::DataType< ::test1::Stock > 
template<>
struct DataType< ::test1::StockResponse>
{
  static const char* value()
  {
    return DataType< ::test1::Stock >::value();
  }
  static const char* value(const ::test1::StockResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST1_MESSAGE_STOCK_H
