; Auto-generated. Do not edit!


(cl:in-package khi_rs007l_moveit_config3-msg)


;//! \htmlinclude autodriverGoal.msg.html

(cl:defclass <autodriverGoal> (roslisp-msg-protocol:ros-message)
  ((samples
    :reader samples
    :initarg :samples
    :type cl:integer
    :initform 0))
)

(cl:defclass autodriverGoal (<autodriverGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <autodriverGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'autodriverGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name khi_rs007l_moveit_config3-msg:<autodriverGoal> is deprecated: use khi_rs007l_moveit_config3-msg:autodriverGoal instead.")))

(cl:ensure-generic-function 'samples-val :lambda-list '(m))
(cl:defmethod samples-val ((m <autodriverGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader khi_rs007l_moveit_config3-msg:samples-val is deprecated.  Use khi_rs007l_moveit_config3-msg:samples instead.")
  (samples m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <autodriverGoal>) ostream)
  "Serializes a message object of type '<autodriverGoal>"
  (cl:let* ((signed (cl:slot-value msg 'samples)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <autodriverGoal>) istream)
  "Deserializes a message object of type '<autodriverGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'samples) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<autodriverGoal>)))
  "Returns string type for a message object of type '<autodriverGoal>"
  "khi_rs007l_moveit_config3/autodriverGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'autodriverGoal)))
  "Returns string type for a message object of type 'autodriverGoal"
  "khi_rs007l_moveit_config3/autodriverGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<autodriverGoal>)))
  "Returns md5sum for a message object of type '<autodriverGoal>"
  "32c9b10ef9b253faa93b93f564762c8f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'autodriverGoal)))
  "Returns md5sum for a message object of type 'autodriverGoal"
  "32c9b10ef9b253faa93b93f564762c8f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<autodriverGoal>)))
  "Returns full string definition for message of type '<autodriverGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%int32 samples~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'autodriverGoal)))
  "Returns full string definition for message of type 'autodriverGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%int32 samples~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <autodriverGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <autodriverGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'autodriverGoal
    (cl:cons ':samples (samples msg))
))
