// Auto-generated. Do not edit!

// (in-package khi_rs007l_moveit_config3.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class autodriverResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.resu = null;
    }
    else {
      if (initObj.hasOwnProperty('resu')) {
        this.resu = initObj.resu
      }
      else {
        this.resu = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type autodriverResult
    // Serialize message field [resu]
    bufferOffset = _serializer.int32(obj.resu, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type autodriverResult
    let len;
    let data = new autodriverResult(null);
    // Deserialize message field [resu]
    data.resu = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'khi_rs007l_moveit_config3/autodriverResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '4bc5b3fe34aee0ff5196e0a80c35caf3';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #result definition
    int32 resu
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new autodriverResult(null);
    if (msg.resu !== undefined) {
      resolved.resu = msg.resu;
    }
    else {
      resolved.resu = 0
    }

    return resolved;
    }
};

module.exports = autodriverResult;
