// Generated by gencpp from file xarm_msgs/GetDigitalIOResponse.msg
// DO NOT EDIT!


#ifndef XARM_MSGS_MESSAGE_GETDIGITALIORESPONSE_H
#define XARM_MSGS_MESSAGE_GETDIGITALIORESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xarm_msgs
{
template <class ContainerAllocator>
struct GetDigitalIOResponse_
{
  typedef GetDigitalIOResponse_<ContainerAllocator> Type;

  GetDigitalIOResponse_()
    : digital_1(0)
    , digital_2(0)
    , ret(0)
    , message()  {
    }
  GetDigitalIOResponse_(const ContainerAllocator& _alloc)
    : digital_1(0)
    , digital_2(0)
    , ret(0)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _digital_1_type;
  _digital_1_type digital_1;

   typedef int32_t _digital_2_type;
  _digital_2_type digital_2;

   typedef int16_t _ret_type;
  _ret_type ret;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::xarm_msgs::GetDigitalIOResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xarm_msgs::GetDigitalIOResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetDigitalIOResponse_

typedef ::xarm_msgs::GetDigitalIOResponse_<std::allocator<void> > GetDigitalIOResponse;

typedef boost::shared_ptr< ::xarm_msgs::GetDigitalIOResponse > GetDigitalIOResponsePtr;
typedef boost::shared_ptr< ::xarm_msgs::GetDigitalIOResponse const> GetDigitalIOResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xarm_msgs::GetDigitalIOResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xarm_msgs::GetDigitalIOResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace xarm_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'xarm_msgs': ['/home/mslab/catkin_ws/src/xarm_ros/xarm_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::xarm_msgs::GetDigitalIOResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xarm_msgs::GetDigitalIOResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xarm_msgs::GetDigitalIOResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xarm_msgs::GetDigitalIOResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xarm_msgs::GetDigitalIOResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xarm_msgs::GetDigitalIOResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xarm_msgs::GetDigitalIOResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5c2bfd923228c71a217e97a1d1747b99";
  }

  static const char* value(const ::xarm_msgs::GetDigitalIOResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5c2bfd923228c71aULL;
  static const uint64_t static_value2 = 0x217e97a1d1747b99ULL;
};

template<class ContainerAllocator>
struct DataType< ::xarm_msgs::GetDigitalIOResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xarm_msgs/GetDigitalIOResponse";
  }

  static const char* value(const ::xarm_msgs::GetDigitalIOResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xarm_msgs::GetDigitalIOResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
int32 digital_1\n\
\n\
int32 digital_2\n\
\n\
int16 ret\n\
\n\
string message\n\
\n\
";
  }

  static const char* value(const ::xarm_msgs::GetDigitalIOResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xarm_msgs::GetDigitalIOResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.digital_1);
      stream.next(m.digital_2);
      stream.next(m.ret);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetDigitalIOResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xarm_msgs::GetDigitalIOResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xarm_msgs::GetDigitalIOResponse_<ContainerAllocator>& v)
  {
    s << indent << "digital_1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.digital_1);
    s << indent << "digital_2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.digital_2);
    s << indent << "ret: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ret);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XARM_MSGS_MESSAGE_GETDIGITALIORESPONSE_H
